// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySHop.Data;

#nullable disable

namespace MySHop.Migrations
{
    [DbContext(typeof(MyShopContext))]
    [Migration("20260126145611_SeedDataCategory")]
    partial class SeedDataCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MySHop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "لباس زنانه",
                            Title = "لباس زنانه"
                        },
                        new
                        {
                            Id = 2,
                            Description = "لباس مردانه",
                            Title = "لباس مردانه"
                        },
                        new
                        {
                            Id = 3,
                            Description = "لباس بچه گانه",
                            Title = "لباس بچه گانه"
                        },
                        new
                        {
                            Id = 4,
                            Description = "لباس نوزاد",
                            Title = "لباس نوزاد "
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
